version: '2'

volumes:
  nextcloud:
  db:

# unsere Container
services:

  app:
    # Nextcloud-Image ohne Webserver Apache2
    # Webserver wird über separaten Container 
    # bereitgestellt
    image: nextcloud:fpm
    # Docker versucht den Container neu zu starten falls er z.B. crashed
    restart: always
    # Inhalt des Verzeichnisses /var/www/html *im Container*
    # wird gespiegelt im lokalen Verzeichnis nextcloud-data
    # So stellen wir sicher, dass Daten nicht verloren gehen
    # und wir einfachen Zugriff darauf haben
    volumes:
      - ./nextcloud-data:/var/www/html
    # Aliase, nicht unbedingt nötig:
    # Sorgt dafür, dass aus dem Container app, der Container db über den Namen 
    # db und database erreichbar ist
    links:
      - db:database
    # Umgebungsvariablen, hier dafür, dass Nextcloud Zugriff auf die 
    # Datenbank erhält
    # Gleichen Angaben, wie bei manuellen Installation, 
    # müssen mit denen des Datenbankcontainers übereinstimmen
    environment:
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=kai
      - NEXTCLOUD_ADMIN_PASSWORD=kai

  db:
    image: mariadb:10.5
    restart: always
    # So aus der Doku übernommen, für den ordnungsgemäßen Betrieb von MariaDB
    # genaue Bedeutung ist hier nicht wichtig
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwdb
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius

  webserver:
    image: nginx
    restart: always
    # Portmapping: Wir erreichen den Container von ausßerhalb über den Port 8888
    # Webserver lauscht im Docker-Netzwerk auf Port 80
    ports:
      - 8888:80
    # Hier binden wir diesmal kein Verzeichnis ein, sondern die Konfigurationsdatei
    # für den Webserver nginx. 1:1 aus Doku übernommen
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud-data:/var/www/html
    # Verlinkung der Container, veraltet, nicht unbedingt nötig:
    links:
      - app
    # Zugriff auf die Volumes des nextcloud containers
    # nötig, damit die Dateien vom Webserver ausgeliefert
    # werden können
    # Alternative zum zweiten Volume ./nextcloud-data:/var/www/html
    #volumes_from:
      #- app
