version: '3.7'

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    networks:
      - wordpress

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw 
      - MYSQL_DATABASE=wordpress 
      - MYSQL_USER=wordi 
      - MYSQL_PASSWORD=wordipw
    networks:
      - wordpress


networks:
  wordpress:
    driver: bridge
